name: test server CI/CD 

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

env:
  S3_BUCKET_NAME: music-soulmate

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Grant execute permission for mvnw
      run: chmod +x mvnw
    - name: Build with Maven
      run: ./mvnw clean package
